---

- name: Download NeoGo binary
  ansible.builtin.get_url:
    url: '{{ neogo__bin_url }}'
    dest: '{{ neogo__bin_path }}'
    force: yes
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]
  when: not (neogo__use_compose | bool)
