---

- name: Install NeoGo binary
  ansible.builtin.get_url:
    url: "{{ neogo__bin_url }}"
    dest: "{{ neogo__bin_path }}"
    force: yes
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: not (neogo__use_compose | bool)
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]
