---

- name: Install NeoGo binary
  ansible.builtin.get_url:
    url: "{{ neogo__bin_url }}"
    dest: "{{ neogo__bin_path }}"
    mode: '0755'
    owner: 'root'
    group: 'root'
  when: not (neogo__use_compose | bool)
  notify:
    - Restart NeoGo service
