---

- ansible.builtin.include_tasks: user.yml

- name: Create configuration directory parent
  ansible.builtin.file:
    state: directory
    path: '{{ neogo__conf_dir | realpath | dirname }}'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Create configuration directory
  ansible.builtin.file:
    state: directory
    path: '{{ neogo__conf_dir }}'
    owner: 'root'
    group: '{{ neogo__group }}'
    mode: '0750'

- ansible.builtin.include_tasks: binary.yml
- ansible.builtin.include_tasks: wallet.yml
- ansible.builtin.include_tasks: tls.yml

- name: Copy NeoGo config
  ansible.builtin.template:
    src: 'protocol.network.yml.j2'
    dest: '{{ neogo__conf_dir }}/protocol.{{ neogo__network }}.yml'
    owner: 'root'
    group: '{{ neogo__group }}'
    mode: '0640'
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]

- name: Copy compose file
  ansible.builtin.template:
    src: 'docker-compose.yml.j2'
    dest: '{{ neogo__conf_dir }}/docker-compose.yml'
    owner: 'root'
    group: '{{ neogo__group }}'
    mode: '0640'
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]
  when: neogo__use_compose | bool

- name: Copy regular systemd unit
  ansible.builtin.template:
    src: 'neogo.service.j2'
    dest: '/etc/systemd/system/neogo{{ neogo__instance }}.service'
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]
  when: not (neogo__use_compose | bool)

- name: Copy dockerized systemd unit
  ansible.builtin.template:
    src: 'neogo_compose.service.j2'
    dest: '/etc/systemd/system/neogo{{ neogo__instance }}.service'
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]
  when: neogo__use_compose | bool

- name: Save debops.ferm rules as facts
  tags: [ 'role::ferm', 'skip::ferm' ]
  ansible.builtin.set_fact:
    neogo__ferm__rules: '{{ neogo__ferm__rules|d([]) + neogo__ferm__dependent_rules }}'
