---

- name: Copy TLS key & certificate
  block:
    - name: Copy TLS key
      ansible.builtin.copy:
        src: '{{ neogo__tls_key }}'
        dest: '{{ neogo__tls_key_file }}'
        owner: 'root'
        group: '{{ neogo__group }}'
        mode: '0640'
    - name: Copy TLS cert
      ansible.builtin.copy:
        src: '{{ neogo__tls_cert }}'
        dest: '{{ neogo__tls_cert_file }}'
        owner: 'root'
        group: '{{ neogo__group }}'
        mode: '0640'
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]
  when: neogo__tls_enabled | bool
