---

- name: Copy wallet
  ansible.builtin.copy:
    dest: "{{ neogo__wallet_path }}"
    content: "{{ neogo__wallet_struct | to_nice_json(ensure_ascii=False) }}"
    owner: 'root'
    group: "{{ neogo__group }}"
    mode: '0660' # neogo legacy wants write permissions
  when: >
    (neogo__wallet_struct is defined) and
    (neogo__wallet_struct|length > 0)
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]
