---

- name: Copy NeoGo wallet
  ansible.builtin.copy:
    content: '{{ neogo__wallet_struct | to_nice_json(ensure_ascii=False) }}'
    dest: '{{ neogo__wallet_path }}'
    owner: 'root'
    group: '{{ neogo__group }}'
    mode: '0660' # neogo legacy wants write permissions
  when: neogo__wallet_struct|length
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]
