---

- name: Copy NeoGo wallet
  ansible.builtin.copy:
    src: '{{ neogo__wallet }}'
    dest: '{{ neogo__wallet_path }}'
    owner: 'root'
    group: '{{ neogo__group }}'
    mode: '0660' # neogo legacy wants write permissions
  when: neogo__wallet|length
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]
