---

- name: Copy wallet
  ansible.builtin.copy:
    dest: "{{ neogo__wallet_path }}"
    content: "{{ neogo__wallet_content }}"
    owner: 'root'
    group: "{{ neogo__group }}"
    mode: '0640'
  when: >
    (neogo__wallet_content is defined) and
    (neogo__wallet_content|length > 0)
  notify:
    - Restart NeoGo service
